baseURL = "https://rizwan.studio/philosophy/"
languageCode = "en-us"
paginate = 5
publishDir = "docs"
theme = "ink"
title = "Rizwan Hasan"

copyright = "© All Rights Reserved"

pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "vs"

# disqusShortname = "ink-demo"
# googleAnalytics = "UA-***-**"

[params]
favicon = "favicon.png"
subtitle = "An archive of my Philosophies"

# Optional 64x64 avatar image.
avatar = "https://avatars2.githubusercontent.com/u/16849373?s=460&v=4"

# Your Disqus sortname.
# disqusShortname = "***"

# Content types to disable Disqus on.
disableDisqusTypes = ["page"]
featherIconsCDN = true

mode = "dark" # "dark" or "auto"
# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Philosophy"
url = "/posts"
weight = 2

[[menu.main]]
name = "About Me"
url = "https://rizwan-hasan.github.io"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/@Linux_Saikat"

[[params.social]]
icon = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/rizwan486/"

[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/Rizwan-Hasan/"

# [[params.social]]
# icon = "send"
# name = "Telegram"
# url = "https://t.me/rizwan486"

# [[params.social]]
# icon = "book-open"
# name = "Dev-to"
# url = "https://dev.to/rizwan486"

[[params.social]]
icon = "rss"
name = "RSS"
url = "/index.xml"

[taxonomies]
tag = "tags"
