baseURL = "https://rizwan-hasan.github.io/philosophy/"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "anatole"
publishDir = "docs"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

## Enable Disqus
# disqusShortname = ""

## Google Analytics
# googleAnalytics = "UA-123-45"

[params]
title = "Rizwan Hasan"
author = "Rizwan Hasan"
copyright = "2022"
description = "An archive of my Observations and Thoughts"
profilePicture = "https://avatars.githubusercontent.com/u/16849373?v=4"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
mainSections = ["posts"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/rizwan486/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "instagram"
url = "https://twitter.com/@Linux_Saikat"

[[params.socialIcons]]
icon = "fab fa-telegram-plane"
title = "Telegram"
url = "https://t.me/rizwan486"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/Rizwan-Hasan/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:rizwan.hasan486@gmail.com"

## Menu items

[menu]

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "All Posts"
weight = 200
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "Tags"
weight = 200
identifier = "tags"
url = "/tags/"

[[menu.main]]
name = "About"
weight = 300
identifier = "about"
url = "https://rizwan-hasan.github.io"
